# Generated by Django 3.2 on 2021-05-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210525_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='log_description',
            new_name='long_description',
        ),
    ]
