# Generated by Django 3.2 on 2021-05-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productimagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='products.ProductTagModel', verbose_name='tags'),
        ),
    ]
